version: '3'
services:
  lindb1:
    build: .
    container_name: lindb_1
    command: bash -c "./lind broker run --config broker.toml && ./lind storage run --config storage.toml"
    volumes:
      - /lindb/broker
      - /lindb/storage
      - /tmp
    depends_on:
      - etcd
    links:
      - etcd
    environment:
      ETCD_ENDPOINTS: "http://etcd:2379"
      ETCDCTL_API: 3
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    ports:
      - "2891:2891"
      - "9000:9000"
    expose:
      - "2891"
      - "9000"
  etcd:
    image: quay.io/coreos/etcd
    volumes:
      - /tmp/etcd-data:/etcd-data
    environment:
      ETCD_NAME: infra
      ETCD_DATA_DIR: /tmp/etcd-data
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_INITIAL_CLUSTER: infra=http://etcd:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    ports:
      - 22379:2379
      - 22380:2380
      - 24001:4001
    expose:
      - "2379"
      - "2380"
